config/routes.rb
Swapsea::Application.routes.draw do
  resources :event_logs

  resources :activities

  resources :notices do
    collection do
      get :admin
    end
  end

  resources :notice_acknowledgements

  post 'sms', to: 'sms#index'
  post 'api/v1/import/members', to: 'api#upload_members'
  post 'api/v1/import/awards', to: 'api#upload_awards'
  post 'api/v1/import/patrol-members', to: 'api#upload_patrol_members'
  get 'api/v1/transfer/members', to: 'api#transfer_members'
  get 'api/v1/transfer/awards', to: 'api#transfer_awards'
  get 'api/v1/transfer/patrol-members', to: 'api#transfer_patrol_members'

  get 'ics/:key', to: 'users#ics', as: 'ics'

  resources :clubs do
    collection do
      get :admin
    end
  end

  resources :emails do
    collection do
      post 'send_weekly_patrol_rosters'
      post 'send_weekly_nudge_offers'
      post 'send_weekly_skills_maintenance'
      post 'send_welcome_email_test'
      post 'send_welcome_email'
      get :admin
    end
  end

  resources :outreach_patrol_sign_ups

  resources :outreach_patrols do
    collection do
      get 'admin'
    end
  end

  get 'skills-maintenance', to: 'proficiencies#index'

  resources :proficiency_signups

  resources :proficiencies do
    collection do
      get 'admin'
    end
  end

  get 'switch-user', to: 'selected_user#index', as: 'switch_user'
  post 'selected_user', to: 'selected_user#set'

  get 'token', to: 'home#token'
  get 'auth', to: 'home#token'

  %w[400 402 403 404 405 406 408 422 500 502 503 504 505].each do |code|
    get code, to: 'errors#show', code:
  end

  get 'admin', to: 'admin#index', as: 'admin'

  resources :swaps do
    collection do
      get 'confirmed'
      get 'my-requests'
      get 'my-offers'
    end
  end

  resources :offers do
    member do
      get 'accept'
      post 'decline'
      get 'confirm-accept', to: 'offers#confirm_accept', as: 'confirm_accept'
      get 'confirm-decline', to: 'offers#confirm_decline', as: 'confirm_decline'
      get 'confirm-withdraw', to: 'offers#confirm_withdraw', as: 'confirm_withdraw'
    end
  end

  resources :requests do
    member do
      get 'confirm-cancel', to: 'requests#confirm_cancel', as: 'confirm_cancel'
    end
  end

  resources :patrol_members do
    collection do
      post :import
      get :admin
    end
  end

  resources :patrols do
    collection do
      get :admin
    end
  end

  resources :awards do
    collection do
      post :import
      get :admin
    end
  end

  resources :rosters do
    collection do
      post :import
      get :member
      get :admin
    end
    member do
      get 'patrol'
      get 'report', defaults: { format: 'pdf' }
    end
  end

  resources :reports do
    collection do
      get 'sign-on/:token', to: 'rosters#sign_on_report', as: 'sign_on', defaults: { format: 'pdf' }
    end
  end

  devise_scope :user do
    get 'login', to: 'users/sessions#new', as: 'login'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  get 'activate', to: 'users#activate'

  root 'home#index'
  get 'thanks', to: 'home#thanks'
  get 'registration', to: 'home#registration'
  get 'setup', to: 'home#setup', as: 'setup'
  get 'contact-us', to: 'home#contact_us', as: 'contact_us'
  get 'faq', to: 'home#faq', as: 'faq'
  get 'privacy-policy', to: 'home#privacy_policy', as: 'privacy_policy'
  get 'terms-of-use', to: 'home#terms_of_use', as: 'terms_of_use'

  resources :users do
    collection do
      post :import
      get :admin
    end
  end

  resources :leads do
    collection do
      get :admin
    end
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  load_and_authorize_resource class: false

  def index
    @notices = Notice.visible

    @my_roster = selected_user.custom_roster
    @my_patrol = selected_user.patrol

    # @activities = PublicActivity::Activity.where(club: selected_user.club).limit(10).order('created_at desc')

    @confirmed_offers = Offer.with_club(selected_user.club_id).includes(:user, request: %i[user roster]).with_accepted_status.order(updated_at: :desc).limit(3)

    render layout: 'dashboard'
  end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
  def selected_user_organisation_code
    selected_user.club_id
  end
end

app/views/dashboard/_footer.html.erb
<!-- Footer -->
<div class="footer">
  <div class="row">
    <div class="col-xs-12 text-center">
      <p class="copyright">
      <%= link_to 'Dashboard', dashboard_path %> |
      <%= link_to 'Contact Us', contact_us_path %> |
      <%= link_to 'Terms of Use', terms_of_use_path %> |
      <%= link_to 'Swapsea on GitHub', 'https://github.com/Swapsea/swapsea/', target: '_blank' %>
        <br/>
        &copy; <%= Date.current.year %> Swapsea
      </p>
    </div>
  </div>
</div> <!-- End footer -->

app/views/dashboard/_footer_small.html.erb
<div class="footer">
  <div class="row">
    <div class="col-xs-12 text-center">
      <p class="copyright">
      <%= link_to 'Dashboard', dashboard_path %> |
      <%= link_to 'Contact Us', contact_us_path %> |
      <%= link_to 'Terms of Use', terms_of_use_path %> |
      <%= link_to 'Swapsea on GitHub', 'https://github.com/Swapsea/swapsea/', target: '_blank' %>
      <br/>
        &copy; <%= Date.current.year %> Swapsea
      </p>
    </div>
  </div>
</div>

app/views/dashboard/_my_roster.html.erb
<div class="my-roster">
  <div class="panel panel-default">
    <div class="panel-heading ics">
      <h2>My Roster</h2>
      <%= link_to 'iCal Sync', ics_path(key: selected_user.ics, :format => :ics)  if selected_user.ics.present? && !selected_user.custom_roster.empty? %>
    </div>
    <div class="panel-body">
      <% if !selected_user.has_patrol? %>
        <div class="info-panel">
          <h3>No Patrol?</h3>
          <p>You are not allocated to a patrol currently.</p>
          <p>If you should be, please contact your Club Administration officer to ensure 'Surfguard' and Swapsea is updated.</p>
        </div>
      <% end
      
      if selected_user.custom_roster.empty? %>
        <div class="info-panel">
          <h3>No Patrols?</h3>
          <p>You have no upcoming patrols.</p>
        </div>
      <% else %>
        <div class="rosters">
          <% selected_user.custom_roster.each do |r| %>
            <div class="roster">
              <div class="details col-sm-9 col-xs-9">
                <%= r.start.strftime("%a %d %b") %>
                <br/>
                <%= r.start.strftime("%H:%M") %>
                \- #{r.finish.strftime("%H:%M")}
                <br/>
                <%= r.patrol.name %>
              </div>
              <% if r.requests.where('user_id = ? AND status = ?', selected_user.id, 'open').present? %>
                <%= link_to raw('<div class="vcenter"><i class="fa fa-long-arrow-right"></i><br/>View Request</div>'), request_path(r.requests.where('user_id = ? AND status = ?', selected_user.id, 'open').last), :class => 'col-sm-3 col-xs-3 action action-view-request' %>
              <% else %>
                <%= link_to raw('<i class="fa fa-random"></i><br/>Request Swap'), new_request_path(:roster_id => r.id), :class => 'col-sm-3 col-xs-3 action action-request-swap' %>
              <% end %>
              <div class="clear"></div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/_noticeboard.html.erb
<% cache [ "noticeboard/organisation", selected_user_organisation_code ], expires_in: 30.minutes do %>
<div class="noticeboard">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2>Notice Board</h2>
    </div>
    <div class="panel-body">
      <% @notices.each do |notice| %>
        <div class="notice">
          <h3><%= notice.title %></h3>
          <p>
            <%= notice.desc.html_safe %>
          </p>
          <p>
            <%= link_to notice.link_desc, notice.link %>
          </p>
        </div><!--/.notice -->
      <% end %>
      <% if @notices.empty? %>
        <div class="notice">
          <h3>(Empty)</h3>
          <p>
            If you need to stand on a soapbox and announce to your fellow clubbies something of great interest. Send us an email and we can make it happen.
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div><!--/.noticeboard -->
<% end %>

app/views/dashboard/_privacy.html.erb
<% if (selected_user.has_role? :admin) || (selected_user.has_role? :manager) || (selected_user.has_position? :patrol_captain) || (selected_user.has_position? :vice_captain) %>
  <div class="alert alert-info">
    <b>Privacy Reminder</b><br/>
    <p>As a Patrol Captain/Vice Captain, you have special access to members' personal details. Please respect the privacy of their information.</p>
  </div>
<% end %>

app/views/dashboard/_statistics.html.erb
<% cache [ "statistics/organisation", selected_user_organisation_code ], expires_in: 60.minutes do %>
  <div class="statistics">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2>Statistics</h2>
    </div>

    <div class="panel-body">
      <div class="stats">
        <div class="stat">
          <span class="number confirmed-swaps">
            <%= Request.with_club(selected_user.club_id).with_successful_status.count %>
          </span>
          <span class="title">Confirmed Swaps</span>
        </div>
        <div class="stat">
          <span class="number offers-pending">
            <%= Offer.with_club(selected_user.club_id).with_pending_status.count %>
          </span>
          <span class="title">Offers Pending</span>
        </div>
        <div class="stat">
          <span class="number requests-open">
            <%= Request.with_club(selected_user.club_id).with_open_status.count %>
          </span>
          <span class="title">Requests Open</span>
        </div>
        <% if ( selected_user.club.show_skills_maintenance ) %>
          <div class="stat">
            <span class="number proficiency-signups">
              <%= ProficiencySignup.with_club(selected_user.club_id).all.count %>
            </span>
            <span class="title">Skills Maintenance Signups</span>
          </div>
          <% end %>
            <div class="stat">
              <span class="number proficiency-signups">
                <%= User.with_club(selected_user.club_id).sum(:sign_in_count) %>
              </span>
              <span class="title">Member Logins</span>
            </div>
      </div>
      <div class="clear"></div>
    </div>
  </div>
</div>
<% end %>

app/views/dashboard/_swap_feed.html.erb
<% cache [ "swap_feed", selected_user_organisation_code ], expires_in: 5.minutes do %>
  <div class="swap-feed">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2>Swap Feed</h2>
    </div>
    <div class="panel-body">
      <% @confirmed_offers.each do |offer| %>
      <div class="swap">
        <div class="row">
          <div class="col-xs-12">
            <div class="created-at"><%= time_ago_in_words(offer.updated_at) %> ago</div>
          </div>
        </div>
        <div class="row">
          <div class="request col-xs-5">
            <s class="name"><%= offer.request.user.name %></s> <strong class="name"><%= offer.user.name %></strong><br/>
            <%= offer.request.roster.start.strftime("%a, %d %b %y") %><br/>
            <%= offer.request.roster.start.strftime("%H:%M") %> - <%= offer.request.roster.finish.strftime("%H:%M") %>
          </div>
          <div class="col-xs-2">
          <% if (offer.roster) %>
          <div class="arrows"><i class="fa fa-arrows-h fa-2x"></i></div>
          <% else %>
            <div class="arrows"><i class="fa fa-life-ring fa-2x"></i></div>
          <% end %>
          </div>
          <div class="col-xs-5">
          <% if (offer.roster) %>
            <s class="name"><%= offer.user.name %></s> <strong class="name"><%= offer.request.user.name %></strong><br/>
            <%= offer.roster.start.strftime("%a, %d %b %y") %><br/>
            <%= offer.roster.start.strftime("%H:%M") %> - <%= offer.roster.finish.strftime("%H:%M") %>
            <% else %>
            <i>Sub without swap</i>
            <% end %>
          </div>
        </div><!--/.row -->
      </div><!--/.swap -->
      <% end %>
    </div><!--/.panel-body -->
    <% if @confirmed_offers.empty? %>
    <div class="panel-info">
      <h3>No Swaps yet!</h3>
      <p>
        Be the first to confirm a swap and see your name up in the big lights right here.
      </p>
    </div>
    <% end %>
  </div><!--/.panel -->

</div><!--/.swaps -->
<% end %>

app/views/dashboard/index.html.erb
<% content_for(:title){ "Dashboard" } %>

<% if Rails.env != 'production' %>
<div class="alert alert-warning">
  This is a non-production environment for Swapsea. It is only for testing purposes. No swaps or proficiency signups will be permanent.
</div>
<% end %>

<h1 class="hidden">Dashboard</h1>

<%= render partial: 'privacy' %> 
<div class="row">
  <div class="col-sm-6 col-xs-12"> 

    <div class="my-roster">
      <div class="panel panel-default">
        <div class="panel-heading ics">
          <h2>My Roster</h2><%= link_to 'iCal Sync', ics_path(key: selected_user.ics, :format => :ics)  if selected_user.ics.present? && !selected_user.custom_roster.empty? %>
        </div>
        <div class="panel-body">
          <% if !selected_user.has_patrol? %>

          <div class="info-panel">
            <h3>No Patrol?</h3>
            <p>You are not allocated to a patrol currently.</p>
            <p>If you should be, please contact your Club Administration officer to ensure 'Surfguard' and Swapsea is updated.</p>
          </div>

          <% end
          
          if selected_user.custom_roster.empty? %>

          <div class="info-panel">
            <h3>No Patrols?</h3>
            <p>You have no upcoming patrols.</p>
          </div>

          <% else %>

          <div class="rosters">
            <% selected_user.custom_roster.each do |r| %>
            <div class="roster">

              <div class="details col-sm-9 col-xs-9">
                <%= r.start.strftime("%a %d %b") %><br/>
                <%= r.start.strftime("%H:%M") %> - <%= r.finish.strftime("%H:%M") %><br/>
                <%= r.patrol.name %>
              </div>


              <% if r.requests.where('user_id = ? AND status = ?', selected_user.id, 'open').present? %>

              <%= link_to raw('<div class="vcenter"><i class="fa fa-long-arrow-right"></i><br/>View Request</div>'), request_path(r.requests.where('user_id = ? AND status = ?', selected_user.id, 'open').last), :class => 'col-sm-3 col-xs-3 action action-view-request' %>

              <% else %>

              <%= link_to raw('<i class="fa fa-random"></i><br/>Request Swap'), new_request_path(:roster_id => r.id), :class => 'col-sm-3 col-xs-3 action action-request-swap' %>

              <% end %>
              <div class="clear"></div>
            </div>
            <% end %>
          </div>
          <% end %>
        </div>
      </div>
    </div><!--/.my-roster -->
  </div>

  <div class="col-sm-6 col-xs-12">

    <%= render partial: 'noticeboard' %>

    <%= render partial: 'swap_feed' %>  

    <div class="divider-25"></div>

    <%= render partial: 'statistics' %>      

  </div>
</div><!--/.row -->

<%= render 'footer' %>