config/routes.rb
Swapsea::Application.routes.draw do
  resources :event_logs

  resources :activities

  resources :notices do
    collection do
      get :admin
    end
  end

  resources :notice_acknowledgements

  post 'sms', to: 'sms#index'
  post 'api/v1/import/members', to: 'api#upload_members'
  post 'api/v1/import/awards', to: 'api#upload_awards'
  post 'api/v1/import/patrol-members', to: 'api#upload_patrol_members'
  get 'api/v1/transfer/members', to: 'api#transfer_members'
  get 'api/v1/transfer/awards', to: 'api#transfer_awards'
  get 'api/v1/transfer/patrol-members', to: 'api#transfer_patrol_members'

  get 'ics/:key', to: 'users#ics', as: 'ics'

  resources :clubs do
    collection do
      get :admin
    end
  end

  resources :emails do
    collection do
      post 'send_weekly_patrol_rosters'
      post 'send_weekly_nudge_offers'
      post 'send_weekly_skills_maintenance'
      post 'send_welcome_email_test'
      post 'send_welcome_email'
      get :admin
    end
  end

  resources :outreach_patrol_sign_ups

  resources :outreach_patrols do
    collection do
      get 'admin'
    end
  end

  get 'skills-maintenance', to: 'proficiencies#index'

  resources :proficiency_signups

  resources :proficiencies do
    collection do
      get 'admin'
    end
  end

  get 'switch-user', to: 'selected_user#index', as: 'switch_user'
  post 'selected_user', to: 'selected_user#set'

  get 'token', to: 'home#token'
  get 'auth', to: 'home#token'

  %w[400 402 403 404 405 406 408 422 500 502 503 504 505].each do |code|
    get code, to: 'errors#show', code:
  end

  get 'admin', to: 'admin#index', as: 'admin'

  resources :swaps do
    collection do
      get 'confirmed'
      get 'my-requests'
      get 'my-offers'
    end
  end

  resources :offers do
    member do
      get 'accept'
      post 'decline'
      get 'confirm-accept', to: 'offers#confirm_accept', as: 'confirm_accept'
      get 'confirm-decline', to: 'offers#confirm_decline', as: 'confirm_decline'
      get 'confirm-withdraw', to: 'offers#confirm_withdraw', as: 'confirm_withdraw'
    end
  end

  resources :requests do
    member do
      get 'confirm-cancel', to: 'requests#confirm_cancel', as: 'confirm_cancel'
    end
  end

  resources :patrol_members do
    collection do
      post :import
      get :admin
    end
  end

  resources :patrols do
    collection do
      get :admin
    end
  end

  resources :awards do
    collection do
      post :import
      get :admin
    end
  end

  resources :rosters do
    collection do
      post :import
      get :member
      get :admin
    end
    member do
      get 'patrol'
      get 'report', defaults: { format: 'pdf' }
    end
  end

  resources :reports do
    collection do
      get 'sign-on/:token', to: 'rosters#sign_on_report', as: 'sign_on', defaults: { format: 'pdf' }
    end
  end

  devise_scope :user do
    get 'login', to: 'users/sessions#new', as: 'login'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  get 'activate', to: 'users#activate'

  root 'home#index'
  get 'thanks', to: 'home#thanks'
  get 'registration', to: 'home#registration'
  get 'setup', to: 'home#setup', as: 'setup'
  get 'contact-us', to: 'home#contact_us', as: 'contact_us'
  get 'faq', to: 'home#faq', as: 'faq'
  get 'privacy-policy', to: 'home#privacy_policy', as: 'privacy_policy'
  get 'terms-of-use', to: 'home#terms_of_use', as: 'terms_of_use'

  resources :users do
    collection do
      post :import
      get :admin
    end
  end

  resources :leads do
    collection do
      get :admin
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  load_and_authorize_resource class: false

  def index
    @lead = Lead.new
    render layout: 'application'
  end

  def setup
    render layout: 'blank'
  end

  def faq
    render layout: 'blank'
  end

  def contact_us
    render layout: 'blank'
  end

  def terms_of_use
    render layout: 'blank'
  end

  def registration
    render layout: 'blank'
  end

  def thanks
    render layout: 'basic'
  end

  def privacy_policy
    render layout: 'basic'
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/home/_footer_large.html.erb
<!-- Footer -->
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-5">
        <%= image_tag('swapsea-logo-col-blk.png', :class => "footer-logo") %>
        <p>
          We love the beach, the surf club and we love solving the patrol swap problem with a bit of technology. Swapsea is made with love by current lifesavers and friends. Cheers!
        </p>
        </div>
      <div class="col-sm-3 col-sm-offset-1 col-md-offset-1">
        <ul class="link-list">
          <li class="heading">Connect with us</li>
          <li><a href="https://www.linkedin.com/in/markhudson/"><i class="fa fa-linkedin-square fa-lg"></i> LinkedIn - Mark</a></li>
          <li><a href="https://www.linkedin.com/in/xandercarroll/"><i class="fa fa-linkedin-square fa-lg"></i> LinkedIn - Alex</a></li>
          <li><a href="https://www.linkedin.com/in/ariellfriedman/"><i class="fa fa-linkedin-square fa-lg"></i> LinkedIn - Ariell</a></li>
          <li><a href="https://www.linkedin.com/in/krishofer/"><i class="fa fa-linkedin-square fa-lg"></i> LinkedIn - Kris</a></li>
          <li><a href="https://www.linkedin.com/in/michaelbamford/"><i class="fa fa-linkedin-square fa-lg"></i> LinkedIn - Michael</a></li>
        </ul>
      </div>
      <div class="col-sm-3">
        <ul class="link-list">
          <li class="heading">Contribute</li>
          <li><a href="https://github.com/Swapsea/swapsea/">Swapsea on GitHub</a></li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 text-center">
        <p class="copyright">
          <%= link_to 'Home', root_path %> |
          <%= link_to 'FAQ', faq_path %> |
          <%= link_to 'Setup Guide', setup_path %> |
          <%= link_to 'Contact Us', contact_us_path %> |
          <%= link_to 'Terms of Use', terms_of_use_path %> |
          <%= link_to 'Swapsea on GitHub', 'https://github.com/Swapsea/swapsea/', target: '_blank' %><br/>
          &copy; <%= Date.current.year %> Swapsea
          </p>
      </div>
    </div>
  </div> <!--/.container -->
</div> <!-- End footer -->

app/views/home/_footer_small.html.erb
<!-- Footer -->
<div class="footer">
  <div class="col-xs-12 text-center">
    <p class="copyright">
    <%= link_to 'Home' , root_path %> |
    <%= link_to 'FAQ' , faq_path %> |
    <%= link_to 'Setup Guide' , setup_path %> |
    <%= link_to 'Contact Us' , contact_us_path %> |
    <%= link_to 'Terms of Use' , terms_of_use_path %> |
    <%= link_to 'Swapsea on GitHub' , 'https://github.com/Swapsea/swapsea/' ,
        target: '_blank' %><br />
    &copy; <%= Date.current.year %> Swapsea
    </p>
  </div>

</div> <!-- End footer -->

app/views/home/contact_us.html.erb
<% content_for(:title){ "Contact Us" } %>

<!-- Navbar -->
<div class="navbar navbar-default navbar-fixed-top landing">
  <div class="container page-scroll">
    <a class="main-logo navbar-left" href="/#home"><h1>Swapsea</h1></a>
    <p class="navbar-text navbar-right">
      <% if ENV['ALLOW_LOGIN'] == 'true' %>
        <% if user_signed_in? %>
          <%= link_to dashboard_path, :class => "btn btn-default btn-lg visible-xs" do %>
            <i class="fa fa-sign-in"></i>
          <% end %>
          <span class="hidden-xs">
            <%= link_to 'Dashboard', dashboard_path, :class => "btn btn-default" %>
          </span>
        <% else %>
          <%= link_to login_path, :class => "btn btn-default btn-lg visible-xs" do %>
            <i class="fa fa-sign-in"></i>
          <% end %>
            <span class="hidden-xs">
              <%= link_to 'Login', login_path, :class => "btn btn-default" %>
            </span>
        <% end %>
      <% end %>
    </p>
  </div>
</div> <!-- End navbar -->



<!-- Jumbotron -->
<div class="jumbotron">
  <div class="container">

    <!-- Intro -->
    <div class="row">
      <div class="col-sm-12">
        <h1><%= content_for(:title) %></h1>
      </div>
    </div> <!-- End intro -->

  </div>
</div> <!-- End Jumbotron -->

<div id="faq">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h2>Club Members</h2>
        <ul class="link-list">
        <li><i class="fa fa-bell fa-lg"></i> Click the <b>Ask Swapsea</b> doorbell widget below. <i class="fa fa-arrow-down"></i></li>
        <li><i class="fa fa-life-ring fa-lg"></i> Email <%= mail_to("feedback-6873-bK7yMGSOfxnWFdjZH2LyOyJwYY20WLel@feedback.doorbell.io", 'Member Help') %></li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <h2>Club Administrators</h2>
        <ul class="link-list">
        <li><i class="fa fa-envelope-square fa-lg"></i> Email <%= mail_to("help@swapsea.com.au", 'Club Administrator Help') %></li>
        <li><i class="fa fa-book fa-lg"></i> <%= link_to 'Setup Guide', setup_path %> </li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <h2>Help Us</h2>
        <ul class="link-list">
          <li><i class="fa fa-github-square fa-lg"></i> <a href="https://github.com/Swapsea/swapsea/">Swapsea on GitHub</a></li>
        </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
        <h2>Connect with Us</h2>
          <ul class="link-list">
          <li><a href="https://www.linkedin.com/in/markhudson/"><i class="fa fa-linkedin-square fa-lg"></i> LinkedIn - Mark</a></li>
          <li><a href="https://www.linkedin.com/in/xandercarroll/"><i class="fa fa-linkedin-square fa-lg"></i> LinkedIn - Alex</a></li>
          <li><a href="https://www.linkedin.com/in/ariellfriedman/"><i class="fa fa-linkedin-square fa-lg"></i> LinkedIn - Ariell</a></li>
          <li><a href="https://www.linkedin.com/in/krishofer/"><i class="fa fa-linkedin-square fa-lg"></i> LinkedIn - Kris</a></li>
          <li><a href="https://www.linkedin.com/in/michaelbamford/"><i class="fa fa-linkedin-square fa-lg"></i> LinkedIn - Michael</a></li>
        </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <%= image_tag('swapsea-logo-col-blk.png', :class => "footer-logo") %>
          <p>
            We love the beach, the surf club and we love solving the patrol swap problem with a bit of technology. <br/>
            Swapsea is made with love by current lifesavers and friends. Cheers!
          </p>
        </div>
    </div>
  </div> <!-- container -->

app/views/home/faq.html.erb
<% content_for(:title){ "Frequently Asked Questions (FAQs)" } %>

<!-- Navbar -->
<div class="navbar navbar-default navbar-fixed-top landing">
  <div class="container page-scroll">
    <a class="main-logo navbar-left" href="/#home"><h1>Swapsea</h1></a>
    <p class="navbar-text navbar-right">
      <% if ENV['ALLOW_LOGIN'] == 'true' %>
        <% if user_signed_in? %>
          <%= link_to dashboard_path, :class => "btn btn-default btn-lg visible-xs" do %>
            <i class="fa fa-sign-in"></i>
          <% end %>
          <span class="hidden-xs">
            <%= link_to 'Dashboard', dashboard_path, :class => "btn btn-default" %>
          </span>
        <% else %>
          <%= link_to login_path, :class => "btn btn-default btn-lg visible-xs" do %>
            <i class="fa fa-sign-in"></i>
          <% end %>
            <span class="hidden-xs">
              <%= link_to 'Login', login_path, :class => "btn btn-default" %>
            </span>
        <% end %>
      <% end %>
    </p>
  </div>
</div> <!-- End navbar -->



<!-- Jumbotron -->
<div class="jumbotron">
  <div class="container">

    <!-- Intro -->
    <div class="row">
      <div class="col-sm-12">
        <h1><%= content_for(:title) %></h1>
      </div>
    </div> <!-- End intro -->

  </div>
</div> <!-- End Jumbotron -->

<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <ol class="faq">
        <li class="faq-question">How does it work?</li>
        <li class="faq-answer">
          It takes two people to make a <i>swap</i> in Swapsea. The requestor advertises the patrol they need a swap
          for. Someone else makes an <i>offer</i> to be a Substitute, usually in exchange for another rostered
          patrol.<br />
          If suitable, the requestor then confirms the offer and the deal is on. Both members are notified by email and
          the substitute receives a reminder ahead of their new patrol.</br>
          Of course, members can just be a substitute without requiring a swap. Everyone still receives email
          confirmation, and a reminder before the new rostered patrol.</li>
        <li class="faq-question">Why is Swapsea better?</li>
        <li class="faq-answer">
          Many Clubs use home-grown systems for posting swaps, like Facebook or Google Sheets or worse. These just don't
          work and may not keep member's personal data private. <br />
          Also, Swapsea swaps can't be cancelled (just swap back if you need!), and there are email reminders for
          upcoming patrols as well as nudge emails to encourage successful swaps.<br />
          Finally, Swapsea is <%= link_to 'Open Source on GitHub' , 'https://github.com/Swapsea/swapsea/' %> so you can
            review the code yourself, and contribute to make it even better!</li>
        <li class="faq-question">Why does it work?</li>
        <li class="faq-answer">
          Swapsea works because the Club honours a Swapsea swap as a handshake deal. Patrollers cannot go back on their
          word. Also, by having a reciprocal swap, two people are committed to the change and patrols remain fully
          manned.</li>
        <li class="faq-question">Why use Swapsea?</li>
        <li class="faq-answer">
          Fewer no-shows means adequately resourced patrols, happier members and safer beaches.</li>
        <li class="faq-question">Where is the data coming from?</li>
        <li class="faq-answer">
          Each Club is responsible for keeping Swapsea up to date using "Custom reports" from the SLSA Surfguard system.
          Detailed instructions are provided <%= link_to('on the setup page',setup_path) %>.</li>
        <li class="faq-question">Where is Swapsea hosted?</li>
        <li class="faq-answer">
          Swapsea is hosted on Heroku which is owned by SalesForce. The data centre is in the United States of America.
        </li>
        <li class="faq-question">What about Privacy?</li>
        <li class="faq-answer">
          Swapsea abides by the same Australian Privacy Principles as SLSA and takes privacy extremely seriously. We are
          professional developers who have our own personal data on this system too, and take all necessary precautions
          to keep that data secure and private. See our <%= link_to 'Terms of Use' , terms_of_use_path() %>.</li>
        <li class="faq-question">Do other clubs use Swapsea?</li>
        <li class="faq-answer">
          Yes. Swapsea launched in 2012/13 and has evolved to support clubs in multiple states with special
          requirements.</li>
        <li class="faq-question">How much does it cost?</li>
        <li class="faq-answer">Larger Clubs pay for Swapsea per season to cover hosting and support. Swapsea is free^
          for smaller clubs. ^Conditions apply.</li>
        <li class="faq-question">Who developed Swapsea?</li>
        <li class="faq-answer">
          Swapsea launched in 2013 when some guys from North Bondi Surf Club couldn't believe nobody had done this
          before. Since then Swapsea has facilitated thousands of swaps between hunreds of members.</li>
        <li class="faq-question">Why Swapsea?</li>
        <li class="faq-answer">
          Who doesn't want <%= link_to 'swapsies' ,'https://en.wiktionary.org/wiki/swapsies' %> by the sea?</li>
          <li class="faq-question">How do we get Started?</li>
            <li class="faq-answer">
            Authorised Club representatives should follow instructions <%= link_to('on the setup page',setup_path) %>.</li>
      </ol>
    </div>
  </div>
</div> <!-- container -->

app/views/home/registration.html.erb
<% content_for(:title){ "Club Registration" } %>

<!-- Navbar -->
<div class="navbar navbar-default navbar-fixed-top landing">
  <div class="container page-scroll">
    <a class="main-logo navbar-left" href="/#home"><h1>Swapsea</h1></a>
    <p class="navbar-text navbar-right">
      <% if ENV['ALLOW_LOGIN'] == 'true' %>
        <% if user_signed_in? %>
          <%= link_to dashboard_path, :class => "btn btn-default btn-lg visible-xs" do %>
            <i class="fa fa-sign-in"></i>
          <% end %>
          <span class="hidden-xs">
            <%= link_to 'Dashboard', dashboard_path, :class => "btn btn-default" %>
          </span>
        <% else %>
          <%= link_to login_path, :class => "btn btn-default btn-lg visible-xs" do %>
            <i class="fa fa-sign-in"></i>
          <% end %>
            <span class="hidden-xs">
              <%= link_to 'Login', login_path, :class => "btn btn-default" %>
            </span>
        <% end %>
      <% end %>
    </p>
  </div>
</div> <!-- End navbar -->



<!-- Jumbotron -->
<div class="jumbotron">
  <div class="container">

    <!-- Intro -->
    <div class="row">
      <div class="col-sm-12">
        <h1><%= content_for(:title) %></h1>
      </div>
    </div> <!-- End intro -->

  </div>
</div> <!-- End Jumbotron -->

<div class="container">
		<div class="col-sm-6 col-sm-offset-3">

			<div class="panel panel-info">
				<div class="panel-heading">
          <h3 class="panel-title">Club Administrator Use Only</h3></div>
				<div class="panel-body">Members please login at <%= link_to 'Member Login', login_path %>.</div>
      </div>

      <p>Use this form to register Swapsea for your Club for the first time.</p>

			<script charset="utf-8" type="text/javascript" src="https://js.hsforms.net/forms/embed/v2.js"></script>
			<script>
			hbspt.forms.create({
			region: "na1",
			portalId: "22433851",
			formId: "eaef9c17-0f8c-4a3d-bcf8-adeaa25cf0b9"
			});
			</script>
	    </div>
    </div>
</div>

app/views/home/setup.html.erb
<% content_for(:title){ "Setup Guide" } %>

<!-- Navbar -->
<div class="navbar navbar-default navbar-fixed-top landing">
  <div class="container page-scroll">
    <a class="main-logo navbar-left" href="/#home"><h1>Swapsea</h1></a>
    <p class="navbar-text navbar-right">
      <% if ENV['ALLOW_LOGIN'] == 'true' %>
        <% if user_signed_in? %>
          <%= link_to dashboard_path, :class => "btn btn-default btn-lg visible-xs" do %>
            <i class="fa fa-sign-in"></i>
          <% end %>
          <span class="hidden-xs">
            <%= link_to 'Dashboard', dashboard_path, :class => "btn btn-default" %>
          </span>
        <% else %>
          <%= link_to login_path, :class => "btn btn-default btn-lg visible-xs" do %>
            <i class="fa fa-sign-in"></i>
          <% end %>
            <span class="hidden-xs">
              <%= link_to 'Login', login_path, :class => "btn btn-default" %>
            </span>
        <% end %>
      <% end %>
    </p>
  </div>
</div> <!-- End navbar -->



<!-- Jumbotron -->
<div class="jumbotron">
  <div class="container">

    <!-- Intro -->
    <div class="row">
      <div class="col-sm-12">
        <h1><%= content_for(:title) %></h1>
        <p class="heading">
		<p>Season <strong>2023/24</strong></p>
      </div>
    </div> <!-- End intro -->

  </div>
</div> <!-- End Jumbotron -->



<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
		<div class="terms-of-use">
			<p>This guide is for Club Administrators to get setup on Swapsea.
			Setup is done each Season even if your Club used Swapsea before as there are changes from year to year.</p>
			<p>This guide is divided into sections:</p>
			<ul>
			<li><b>Registration</b> - every Club, every season.</li>
			<li><b>Pre Season</b> - Surfguard reports, information for PCs, VCs and patrolling members.</li>
			<li><b>During the Season</b> - Operations and Support</li>
			<li><b>End of Season</b> - Stopping Surfguard reports and obtaining usage.</li>
			</ul>
			<p>If you have questions, please contact <%= mail_to "help@swapsea.com.au", "help@swapsea.com.au" %>.</p>

			<hr/>

			<h2>Registration</h2>

			<p><b>New to Swapsea?</b> Please complete the Club Registration form and await further instructions.</p>
			<%= link_to 'Club Registration', registration_path, :class => 'btn btn-success btn-lg' %>
			</p>

			<p><br/><b>Returning Clubs</b> please email <%= mail_to "help@swapsea.com.au", "help@swapsea.com.au", subject: "Club Registration" %> and let us know:</p>

			<ol>
			<li><b>Primary Contact</b> - Nominate who will be responsible for Swapsea at your Club. This is normally the Club Captain or Head of Lifesaving.</li>
			<li><b>Managers</b> - Nominate members who can maintain the Skills Maintenance Sign ups. Note: Cancelling a confirmed Swap is not possible.</li>
			<li><b>Skills Maintenance?</b> - Enable Swapsea to be used for training timeslot signups with place limits to precent crowding.</li>
			<li><b>Outreach Patrols?</b> - Enable Swapsea to be used for additional, special events like Carnivals or Outreach patrols outside the rostered patrols.</li>
			<li><b>SMS Reminders?</b> - Enable SMS reminders for upcoming patrols or Skills Maintenance sessions. Additional usage charges apply.</li>
			</ol>

			<hr/>

			<h2>Pre-Season</h2>
			<p>Swapsea makes patrol swaps easy. It does this by using members' personal data from Surfguard. Swapsea needs to be refreshed periodically to include new members, new awards and updated contact information.</p>
			<h4>SurfGuard Custom Reports</h4>
			<ol>
				<li>Download reports bundle: <i class="fa fa-file-archive-o fa-lg"></i> <%= link_to 'swapsea_custom_reports_2023.zip', 'downloads/swapsea_custom_reports_2023.zip' %></li><br/>
				<li>Unzip / extract the bundle. You should have four (4) report templates:
					<ol type="i">
						<li>custom_report_awards_2023.xml</li>
						<li>custom_report_members_2023.xml</li>
						<li>custom_report_patrol_teams_2023.xml</li>
						<li>custom_report_rosters_2023.xml</li>
					</ol><br />
				</li>
				<li>Log in to Surfguard:<br/>
				<%= link_to 'https://surfguard.slsa.asn.au/SLSA_Admin/modules/login/newLogin.php', 'https://surfguard.slsa.asn.au/SLSA_Admin/modules/login/newLogin.php' %></li><br />
				<li>Under the <b>Reports</b> menu, choose <b>Custom Reports</b>
				<%= image_tag('surfguard-custom-1.png', width: "90%") %></li>
				<li>Load each saved template file, and press Go
				<%= image_tag('surfguard-custom-2.png', width: "90%") %></li>
				<li>Confirm the options below:
				<ol type="a">
					<li><b>Send Report Via Email</b>: help@swapsea.com.au</li><br/>
					<li><b>Recurring Type</b>: Weekly (awards, members & patrol teams only).<br/>
					Nb. The Rosters report <u>must not</u> be recurring. <br/>
					Contact Support if you have a roster
					change after initial setup.</li><br/>
					<li><b>Display Type</b>: Downloadable CSV (Excel Format)</li><br/>
					<li><b>Create Template</b>: Untick.</li>
				</ol>
				<%= image_tag('surfguard-custom-3.png', width: "90%") %>
				<div class="panel panel-warning">
					<div class="panel-heading"><h3 class="panel-title">Privacy Notice</h3></div>
					<div class="panel-body">To maintain the privacy and security of member information, please do not email the reports to
					Swapsea yourself. Just let Surfguard send the reports directly and we'll let you know when it's arrived.</div>
				</div>
			</ol>

			<hr/>
			<h2>During the Season</h2>
			<p><b>Monday mornings</b>: Offer Nudge emails are sent prompting members with an open request to make an offer.</p>
			
			<p><b>Wednesday mornings</b>: Swapsea refreshes from Surfguard using the custom reports scheduled above.</p>

			<p><b>Thursday mornings</b>: Reminder emails are sent to all members with a Patrol or Skills Maintenance session in the next seven (7) days. Usage of Swapsea peaks on a Thursday!</p>
			
			<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title">Advertise Swapsea to Members</h3></div>
					<div class="panel-body">
					Reminder members about Swapsea around your clubhouse, in your newsletter/socials and PC/VC briefing. For example: <br/>
					<b>Need a Swap? <%= link_to 'Swap it on Swapsea','https://www.swapsea.com.au' %></b><br />
					Confirmed swaps on Swapsea still count toward 100% attendance.</p>
					</div>
			</div>
			<p>Tips:</p>
			<ul>
			<li>Members may share an email address, often a parent and child. If so, when logging in they will be asked to 'switch to' one member. They can 'switch back' at any time from the top right menu.</li>
			<li>If the number of Open Swaps is higher than the number of Offers, remind patrollers that they must make an Offer to get a swap. 
			Nobody will get a Swap if nobody makes an Offer... this is why Swapsea sends nudges.</li>
			<li>Nominate 'Managers' to manage sign ups for Skills Maintenance and Extra Patrols.</li>
			</ul>
			<hr/>

			<h2>End of Season</h2>
			<p>At the end of the season, please delete the Scheduled Background Reports.
			<ol>
				<li>From Surfguard home, go to <b>Maintenance > Background Reports > Scheduled
		   		Background Reports</b>
				   <%= image_tag('surfguard-custom-4.png', width: "90%") %>
				</li>
		   		<li>Click Delete beside each Swapsea report, name like:
					<ul>
						<li>swapsea_awards</li>
						<li>swapsea_members</li>
						<li>swapsea_patrols</li>
					</ul>
		  		<li>Click <b>Delete</b> again, and click the link to return.
				  <%= image_tag('surfguard-custom-5.png', width: "90%") %>
				</li>
		  	</ol>
			</p>
			<p>Invoices (if applicable) are sent at the completion of the season, payable within 7 days.</p>
	   	</div>
	</div>
</div>

app/views/home/thanks.html.erb
<div class="container">
		<div class="col-sm-6 col-sm-offset-3">
	        <div class="panel panel-default">
	        	<div class="panel-heading">
	        		<h2>Registration Received!</h2>
	        	</div>
	        	<div class="panel-body">
	        		<p>
	        			Thank you for registering your Club with Swapsea.
	        		</p>
	        		<p>
	        			Someone from our volunteer team will contact you shortly to continue the registration process.
	        		</p>
	        		<p>
	        			<%= link_to 'Back to Setup', setup_path %>
	        		</p>
	    		</div>
	        </div>
	    </div>
    </div>
</div>

app/views/home/token.html.erb
<div class="container">
    <div class="full-content-center animated fadeIn">
        <%= image_tag('alternate-logo.png', :class => "modal-logo") %>
        <div class="box-info">
        	<p>Club logins are no longer available. To login use the link below.</p>
        	<%= link_to 'Login', new_user_session_path %><br/>
        	<%= link_to 'Home', root_path %>
        </div>
    </div>
</div>