config/routes.rb
Swapsea::Application.routes.draw do
  resources :event_logs

  resources :activities

  resources :notices do
    collection do
      get :admin
    end
  end

  resources :notice_acknowledgements

  post 'sms', to: 'sms#index'
  post 'api/v1/import/members', to: 'api#upload_members'
  post 'api/v1/import/awards', to: 'api#upload_awards'
  post 'api/v1/import/patrol-members', to: 'api#upload_patrol_members'
  get 'api/v1/transfer/members', to: 'api#transfer_members'
  get 'api/v1/transfer/awards', to: 'api#transfer_awards'
  get 'api/v1/transfer/patrol-members', to: 'api#transfer_patrol_members'

  get 'ics/:key', to: 'users#ics', as: 'ics'

  resources :clubs do
    collection do
      get :admin
    end
  end

  resources :emails do
    collection do
      post 'send_weekly_patrol_rosters'
      post 'send_weekly_nudge_offers'
      post 'send_weekly_skills_maintenance'
      post 'send_welcome_email_test'
      post 'send_welcome_email'
      get :admin
    end
  end

  resources :outreach_patrol_sign_ups

  resources :outreach_patrols do
    collection do
      get 'admin'
    end
  end

  get 'skills-maintenance', to: 'proficiencies#index'

  resources :proficiency_signups

  resources :proficiencies do
    collection do
      get 'admin'
    end
  end

  get 'switch-user', to: 'selected_user#index', as: 'switch_user'
  post 'selected_user', to: 'selected_user#set'

  get 'token', to: 'home#token'
  get 'auth', to: 'home#token'

  %w[400 402 403 404 405 406 408 422 500 502 503 504 505].each do |code|
    get code, to: 'errors#show', code:
  end

  get 'admin', to: 'admin#index', as: 'admin'

  resources :swaps do
    collection do
      get 'confirmed'
      get 'my-requests'
      get 'my-offers'
    end
  end

  resources :offers do
    member do
      get 'accept'
      post 'decline'
      get 'confirm-accept', to: 'offers#confirm_accept', as: 'confirm_accept'
      get 'confirm-decline', to: 'offers#confirm_decline', as: 'confirm_decline'
      get 'confirm-withdraw', to: 'offers#confirm_withdraw', as: 'confirm_withdraw'
    end
  end

  resources :requests do
    member do
      get 'confirm-cancel', to: 'requests#confirm_cancel', as: 'confirm_cancel'
    end
  end

  resources :patrol_members do
    collection do
      post :import
      get :admin
    end
  end

  resources :patrols do
    collection do
      get :admin
    end
  end

  resources :awards do
    collection do
      post :import
      get :admin
    end
  end

  resources :rosters do
    collection do
      post :import
      get :member
      get :admin
    end
    member do
      get 'patrol'
      get 'report', defaults: { format: 'pdf' }
    end
  end

  resources :reports do
    collection do
      get 'sign-on/:token', to: 'rosters#sign_on_report', as: 'sign_on', defaults: { format: 'pdf' }
    end
  end

  devise_scope :user do
    get 'login', to: 'users/sessions#new', as: 'login'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  get 'activate', to: 'users#activate'

  root 'home#index'
  get 'thanks', to: 'home#thanks'
  get 'registration', to: 'home#registration'
  get 'setup', to: 'home#setup', as: 'setup'
  get 'contact-us', to: 'home#contact_us', as: 'contact_us'
  get 'faq', to: 'home#faq', as: 'faq'
  get 'privacy-policy', to: 'home#privacy_policy', as: 'privacy_policy'
  get 'terms-of-use', to: 'home#terms_of_use', as: 'terms_of_use'

  resources :users do
    collection do
      post :import
      get :admin
    end
  end

  resources :leads do
    collection do
      get :admin
    end
  end
end

app/models/proficiency.rb
# frozen_string_literal: true

class Proficiency < ApplicationRecord
  belongs_to :club
  has_many :proficiency_signups
  has_many :users, through: :proficiency_signups

  scope :with_club, ->(club_id) { where(club_id:).includes(:proficiency_signups, :users) }
end

app/controllers/proficiencies_controller.rb
# frozen_string_literal: true

class ProficienciesController < ApplicationController
  load_and_authorize_resource
  before_action :set_proficiency, only: %i[show edit update destroy]
  layout 'dashboard'

  # GET /proficiencies
  # GET /proficiencies.json
  def index
    @proficiencies = if selected_user.has_role?(:admin)
                       Proficiency.with_club(selected_user.club).all
                     elsif selected_user.has_role?(:manager)
                       Proficiency.with_club(selected_user.club).all.where('start >= ?', DateTime.now - 10.days)
                     else
                       Proficiency.with_club(selected_user.club).all.where('start >= ?', DateTime.now - 10.minutes)
                     end

    @proficiencies_sorted = @proficiencies.sort_by(&:start)
    @uniq_proficiency_dates = @proficiencies_sorted.map { |d| d.start.strftime('%d %b %y') }.uniq
    @proficiency_signup = ProficiencySignup.new
  end

  def admin
    @proficiencies = if selected_user.has_role?(:admin)
                       Proficiency.all.includes(:proficiency_signups, :users, :club).order(:start)
                     elsif selected_user.has_role?(:manager)
                       Proficiency.with_club(selected_user.club).all.includes(:proficiency_signups, :users, :club).where('start >= ?', DateTime.now - 12.hours)
                     end

    render layout: 'admin'
  end

  # GET /proficiencies/1
  # GET /proficiencies/1.json
  def show; end

  # GET /proficiencies/new
  def new
    @proficiency = Proficiency.new
    render layout: 'admin'
  end

  # GET /proficiencies/1/edit
  def edit
    render layout: 'admin'
  end

  # POST /proficiencies
  # POST /proficiencies.json
  def create
    @proficiency = Proficiency.new(proficiency_params)

    respond_to do |format|
      if @proficiency.save
        format.html do
          redirect_to admin_proficiencies_path, notice: 'Skill Maintenance Session was successfully created.'
        end
        format.json { render action: 'index', status: :created, location: @proficiency }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /proficiencies/1
  # PATCH/PUT /proficiencies/1.json
  def update
    respond_to do |format|
      if @proficiency.update(proficiency_params)
        format.html do
          redirect_to admin_proficiencies_path, notice: 'Skill Maintenance Session was successfully updated.'
        end
      else
        format.html { render admin_proficiencies_path, notice: 'There was an error.' }
      end
    end
  end

  # DELETE /proficiencies/1
  # DELETE /proficiencies/1.json
  def destroy
    respond_to do |format|
      # if there are sign ups, don't allow destroy
      if @proficiency.proficiency_signups.count.zero?
        @proficiency.destroy
        format.html { redirect_to admin_proficiencies_path }
      else
        format.html { render admin_proficiencies_path, notice: 'Unable to delete proficiency, as there are signups.' }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_proficiency
    @proficiency = Proficiency.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the allowlist through.
  def proficiency_params
    params.require(:proficiency).permit(:name, :start, :finish, :max_signup, :max_online_signup, :club_id)
  end
end

app/helpers/proficiencies_helper.rb
# frozen_string_literal: true

module ProficienciesHelper
end

app/views/proficiencies/_form.html.erb
<%= simple_form_for(@proficiency) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
      <% if selected_user.has_role?(:admin)  %>
				<%= f.association :club, label_method: :name, value_method: :id, include_blank: false %>
			<% else %>
      <%= f.hidden :club, selected_user.club  %>
      <% end %>
    <%= f.input :name %>
    <br/>
    <%= f.input :start, :minute_step => 15 %>
    <br/>
    <%= f.input :finish, :minute_step => 15 %>
    <br/>
    <%= f.input :max_signup %>
    <br/>
    <%= f.input :max_online_signup %>
    <br/>
  </div>
  <br/>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-default' %>
  </div>
  <br/>
<% end %>

app/views/proficiencies/admin.html.erb
<div class="box-info">
<h2>Skills Maintenance</h2>

<%= link_to 'New Time Slot', new_proficiency_path %>

	<div class="panel-body">
		<div class="table-responsive">
			<table class="table table-striped datatable">
  <thead>
    <tr>
      <th>Club</th>
      <th>Name</th>
      <th>Date</td>
      <th>Start</th>
      <th>Finish</th>
      <th>Max signup</th>
      <th>Max online signup</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @proficiencies.each do |proficiency| %>
      <tr>
        <td><%= proficiency.club.name %></td>
        <td><%= proficiency.name %></td>
        <td><%= proficiency.start.strftime('%a %d %b %y') %></td>
        <td><%= proficiency.start.strftime('%H:%M') %></td>
        <td><%= proficiency.finish.strftime('%H:%M') %></td>
        <td><%= proficiency.max_signup %></td>
        <td><%= proficiency.max_online_signup %></td>
        <td><%= link_to 'Edit', edit_proficiency_path(proficiency) %></td>
        <td><%= link_to 'Delete', proficiency, method: :delete, data: { confirm: 'Really delete this?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/proficiencies/edit.html.erb
<div class="box-info">

<h2>Proficiency <%= @proficiency.id %></h2>

<%= render 'form' %>

<%= link_to 'Show', @proficiency %> |
<%= link_to 'Back', admin_proficiencies_path %>

</div>

app/views/proficiencies/index.html.erb
<% content_for(:title){ "Skills Maintenance" } %>

<h2><%= content_for(:title) %></h2>
  <% if @proficiencies.empty? %>
    <div class="box-info">
      <p>There are no timeslots listed yet. Please check again later or contact your Club.</p>
    </div>
  <% else %>
  <p>Select a session and choose <b>Sign Up!</b>.</p>
<div class="proficiencies col-sm-12">
  <% @uniq_proficiency_dates.each do |uniq_proficiency_date| %>

		<% @uniq_proficiency_date_parsed = Date.parse(uniq_proficiency_date) %>
		<% @proficiencies_for_uniq_date = @proficiencies.where(:start => @uniq_proficiency_date_parsed.beginning_of_day..@uniq_proficiency_date_parsed.end_of_day) %>

		<div class="brick col-sm-12 col-xs-12">

		  	<div class="datetime col-sm-2 col-xs-12">
				<div class="day"><%= @uniq_proficiency_date_parsed.strftime("%a") %></div>
				<div class="date"><%= @uniq_proficiency_date_parsed.strftime("%d") %></div>
				<div class="month"><%= @uniq_proficiency_date_parsed.strftime("%b") %></div>
		  	</div>
		  	<div class="events col-sm-9 col-xs-12">

		  		<% @proficiencies_for_uniq_date.sort_by(&:start).each do |p| %>
						<div class="event">
					  		<% if p.name.include? 'Bronze' %>
					  			<div class="name col-sm-2 col-xs-12 bronze"><%= p.name %></div>
					  		<% elsif p.name.include? 'ART' %>
					  			<div class="name col-sm-2 col-xs-12 artc"><%= p.name %></div>
					  		<% elsif p.name.include? 'SRC' %>
					  			<div class="name col-sm-2 col-xs-12 src"><%= p.name %></div>
					  		<% else %>
					  			<div class="name col-sm-2 col-xs-12 default"><%= p.name %></div>
					  		<% end %>

					  		<div class="details col-sm-8 col-xs-12">

								<div class="info col-sm-8 col-xs-12">
							  		<span class="time">
						  				<%= p.start.strftime("%H:%M") %> - <%= p.finish.strftime("%H:%M") %>
							  		</span>
							  		<span class="visible-xs"><%= p.start.strftime("%A %d %B %Y") %></span>
							  		<span><%= raw('<small>Includes Bronze</small>') if p.name == 'ART' %></span>
							  		<span class="positions">
							  		<% if p.max_online_signup - p.proficiency_signups.count >= 1 %>
						  				<%= p.max_online_signup - p.proficiency_signups.count %> <% if p.max_online_signup - p.proficiency_signups.count >= 2 %> places left <% else %> Place Left <% end %>
						  			<% end %>
							  		</span><!--/.positions -->
								</div><!--/.info -->

								<div class="members col-sm-12 col-xs-12">
									<% p.proficiency_signups.each do |ps| %>
										<% if ps.user.present? %>
										<div class="member">

											<div class="user"><%= ps.user.first_name %> <%= ps.user.last_name %></div>
											<% if (selected_user == ps.user)  %>
												<div class="cancel"><%= link_to 'Cancel', ps, method: :delete %></div>
											<% elsif ((selected_user.has_role? :admin) || (selected_user.has_role? :manager)) %>
												<div class="cancel"><%= link_to 'Cancel this sign up', ps, method: :delete %></div>
											<% end %>

										</div><!--/.member -->
										<% end %>
									<% end %>
								</div><!--/.members -->

							</div><!--/.details -->

							<% if (p.max_online_signup - p.proficiency_signups.count >= 1) || ( (p.max_signup - p.proficiency_signups.count >= 1) && ((selected_user.has_role? :admin) || (selected_user.has_role? :manager)) ) %>
								<%= simple_form_for(@proficiency_signup, html: { id: 'proficiency_signup_' + p.id.to_s }) do |f| %>
								 	<div class="signup col-sm-2 col-xs-12">
								  		<%= f.input :proficiency_id, :as => :hidden, :input_html => { value: p.id, id: 'proficiency_id_' + p.id.to_s } %>
								    	<%= f.submit :submit, :value => "Sign Up!", :class => "btn-signup" %>
								  	</div>
								<% end %>
							<% else %>
								<div class="signup col-sm-2 col-xs-12">
								  	<div class="btn-signup signup-full">Full</div>
								</div>
							<% end %>

						</div><!--/.event -->

				<% end %>

			</div><!--/.events -->
		</div><!--/.box -->
  	<% end %>
</div><!--/.proficiencies -->
<% end %>

app/views/proficiencies/new.html.erb
<div class"box-info">

<h2>New proficiency</h2>

<%= render 'form' %>

<%= link_to 'Back', proficiencies_path %>

</div>

app/views/proficiencies/show.html.erb
<div class="box-info">

<h2>Proficiency <%= @proficiency.id %></h2>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @proficiency.name %>
</p>

<p>
  <strong>Start:</strong>
  <%= @proficiency.start %>
</p>

<p>
  <strong>Finish:</strong>
  <%= @proficiency.finish %>
</p>

<p>
  <strong>Max signup:</strong>
  <%= @proficiency.max_signup %>
</p>

<p>
  <strong>Max online signup:</strong>
  <%= @proficiency.max_online_signup %>
</p>

<%= link_to 'Edit', edit_proficiency_path(@proficiency) %> |
<%= link_to 'Back', admin_proficiencies_path %>

</div>