config/routes.rb
Swapsea::Application.routes.draw do
  resources :event_logs

  resources :activities

  resources :notices do
    collection do
      get :admin
    end
  end

  resources :notice_acknowledgements

  post 'sms', to: 'sms#index'
  post 'api/v1/import/members', to: 'api#upload_members'
  post 'api/v1/import/awards', to: 'api#upload_awards'
  post 'api/v1/import/patrol-members', to: 'api#upload_patrol_members'
  get 'api/v1/transfer/members', to: 'api#transfer_members'
  get 'api/v1/transfer/awards', to: 'api#transfer_awards'
  get 'api/v1/transfer/patrol-members', to: 'api#transfer_patrol_members'

  get 'ics/:key', to: 'users#ics', as: 'ics'

  resources :clubs do
    collection do
      get :admin
    end
  end

  resources :emails do
    collection do
      post 'send_weekly_patrol_rosters'
      post 'send_weekly_nudge_offers'
      post 'send_weekly_skills_maintenance'
      post 'send_welcome_email_test'
      post 'send_welcome_email'
      get :admin
    end
  end

  resources :outreach_patrol_sign_ups

  resources :outreach_patrols do
    collection do
      get 'admin'
    end
  end

  get 'skills-maintenance', to: 'proficiencies#index'

  resources :proficiency_signups

  resources :proficiencies do
    collection do
      get 'admin'
    end
  end

  get 'switch-user', to: 'selected_user#index', as: 'switch_user'
  post 'selected_user', to: 'selected_user#set'

  get 'token', to: 'home#token'
  get 'auth', to: 'home#token'

  %w[400 402 403 404 405 406 408 422 500 502 503 504 505].each do |code|
    get code, to: 'errors#show', code:
  end

  get 'admin', to: 'admin#index', as: 'admin'

  resources :swaps do
    collection do
      get 'confirmed'
      get 'my-requests'
      get 'my-offers'
    end
  end

  resources :offers do
    member do
      get 'accept'
      post 'decline'
      get 'confirm-accept', to: 'offers#confirm_accept', as: 'confirm_accept'
      get 'confirm-decline', to: 'offers#confirm_decline', as: 'confirm_decline'
      get 'confirm-withdraw', to: 'offers#confirm_withdraw', as: 'confirm_withdraw'
    end
  end

  resources :requests do
    member do
      get 'confirm-cancel', to: 'requests#confirm_cancel', as: 'confirm_cancel'
    end
  end

  resources :patrol_members do
    collection do
      post :import
      get :admin
    end
  end

  resources :patrols do
    collection do
      get :admin
    end
  end

  resources :awards do
    collection do
      post :import
      get :admin
    end
  end

  resources :rosters do
    collection do
      post :import
      get :member
      get :admin
    end
    member do
      get 'patrol'
      get 'report', defaults: { format: 'pdf' }
    end
  end

  resources :reports do
    collection do
      get 'sign-on/:token', to: 'rosters#sign_on_report', as: 'sign_on', defaults: { format: 'pdf' }
    end
  end

  devise_scope :user do
    get 'login', to: 'users/sessions#new', as: 'login'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  get 'activate', to: 'users#activate'

  root 'home#index'
  get 'thanks', to: 'home#thanks'
  get 'registration', to: 'home#registration'
  get 'setup', to: 'home#setup', as: 'setup'
  get 'contact-us', to: 'home#contact_us', as: 'contact_us'
  get 'faq', to: 'home#faq', as: 'faq'
  get 'privacy-policy', to: 'home#privacy_policy', as: 'privacy_policy'
  get 'terms-of-use', to: 'home#terms_of_use', as: 'terms_of_use'

  resources :users do
    collection do
      post :import
      get :admin
    end
  end

  resources :leads do
    collection do
      get :admin
    end
  end
end

app/models/award.rb
# frozen_string_literal: true

class Award < ApplicationRecord
  belongs_to :user

  scope :with_user, ->(user_id) { where(user_id:).includes(:user) }

  validates :award_number, uniqueness: true

  def self.upload(file)
    values = []

    columns = %i[award_number award_name user_id award_date proficiency_date expiry_date
                 originating_organisation]

    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(5)
    (6..spreadsheet.last_row).each do |i|
      row = [header, spreadsheet.row(i)].transpose.to_h
      next if row['Award Number'].blank?

      # award = find_by_award_number(row["Award Number"]) || new
      # award.user_id = row["Member ID"]
      # award.award_name = row["Award Name"]
      # award.award_number = row["Award Number"].delete! ?'
      # award.award_date = row["Award Date"]
      # award.proficiency_date = row["Proficiency Date"]
      # award.expiry_date = row["Expiry Date"]
      # award.award_allocation_date = row["Award Allocation Date"]
      # award.proficiency_allocation_date = row["Proficiency Allocation Date"]
      # award.originating_organisation = row["Originating Organisation"]
      # award.save!

      award = [
        row['Award Number'].delete("'"),
        row['Award Name'],
        row['Member ID'],
        row['Award Date'],
        row['Proficiency Date'],
        row['Award Expiry Date'],
        row['Award Originating Organisation']
      ]

      values << award
    end

    Award.import columns, values, validate: true, on_duplicate_key_ignore: true
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when '.txt' then Roo::CSV.new(file.path)
    when '.csv' then Roo::CSV.new(file.path)
    when '.xls' then Roo::Excel.new(file.path)
    when '.xlsx' then Roo::Excelx.new(file.path)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/controllers/awards_controller.rb
# frozen_string_literal: true

class AwardsController < ApplicationController
  load_and_authorize_resource
  before_action :set_award, only: %i[show edit update destroy]
  layout 'dashboard'

  # GET /awards
  # GET /awards.json

  def import
    # @club = params[:club]
    # begin
    Award.upload(params[:file])
    redirect_to admin_awards_path, notice: 'Awards imported.'
    # rescue
    # redirect_to root_url, notice: "Invalid CSV file format."
    # end
  end

  def admin
    @awards = Award.all
    render layout: 'admin'
  end

  # GET /awards/1
  # GET /awards/1.json
  def show; end

  # POST /awards
  # POST /awards.json
  def create
    @award = Award.new(award_params)

    respond_to do |format|
      if @award.save
        format.html { redirect_to @award, notice: 'Award was successfully created.' }
        format.json { render action: 'show', status: :created, location: @award }
      else
        format.html { render action: 'new' }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /awards/1
  # PATCH/PUT /awards/1.json
  def update
    respond_to do |format|
      if @award.update(award_params)
        format.html { redirect_to @award, notice: 'Award was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /awards/1
  # DELETE /awards/1.json
  def destroy
    @award.destroy
    respond_to do |format|
      format.html { redirect_to awards_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_award
    @award = Award.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the allowlist through.
  def award_params
    params.require(:award).permit(:user_id, :award_name, :award_number, :award_date, :proficiency_date, :expiry_date,
                                  :award_allocation_date, :proficiency_allocation_date, :originating_organisation)
  end
end

app/helpers/awards_helper.rb
# frozen_string_literal: true

module AwardsHelper
end

app/views/awards/_form.html.erb
<%= simple_form_for(@award) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :award_name %>
    <%= f.input :award_number %>
    <%= f.input :award_date %>
    <%= f.input :proficiency_date %>
    <%= f.input :expiry_date %>
    <%= f.input :award_allocation_date %>
    <%= f.input :proficiency_allocation_date %>
    <%= f.input :originating_organisation %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/awards/admin.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h2>Import Awards from Surfguard</h2>
	</div>
	<div class="panel-body">
		<%= form_tag import_awards_path, multipart: true do %>
			<p>
				<%= file_field_tag :file, accept: 'text/csv' %>
			</p>
			<p>
				<%= submit_tag "Import CSV", :class => "btn btn-success" %>
			</p>
		<% end %>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		<h2>Awards</strong>
	</div>
	<div class="panel-body">
		<strong>Total Awards:</strong> <%= @awards.count %><br/>
		<strong>Awards added in the last 2 minutes:</strong> <%= @awards.where('created_at >= ?', DateTime.now - 2.minutes).count %><br/>
		<strong>Awards updated in the last 2 minutes:</strong> <%= @awards.where('updated_at >= ?', DateTime.now - 2.minutes).count %>
	</div>
<div>

app/views/awards/edit.html.erb
<h1>Editing award</h1>

<%= render 'form' %>

<%= link_to 'Show', @award %> |
<%= link_to 'Back', awards_path %>

app/views/awards/index.html.erb
<div class="box-info">
  <h2><strong>Awards</strong></h2>
  <div class="table-responsive">
    <table>
      <thead>
        <tr>
          <th>Member ID</th>
          <th>Member First Name</th>
          <th>Member Last Name</th>
          <th>Award Name</th>
          <th>Award Number</th>
        </tr>
      </thead>
      <tbody>

        <% @awards.each do |award| %>

          <tr>
            <td><%= award.user_id %></td>
            <td><%= User.find(award.user_id).first_name %></td>
            <td><%= User.find(award.user_id).last_name %></td>
            <td><%= award.award_name %></td>
            <td><%= award.award_number %></td>
          </tr>

        <% end %>

      </tbody>
    </table>
  </div>
<div>

app/views/awards/new.html.erb
<h1>New award</h1>

<%= render 'form' %>

<%= link_to 'Back', awards_path %>

app/views/awards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @award.user_id %>
</p>

<p>
  <strong>Award name:</strong>
  <%= @award.award_name %>
</p>

<p>
  <strong>Award number:</strong>
  <%= @award.award_number %>
</p>

<p>
  <strong>Award date:</strong>
  <%= @award.award_date %>
</p>

<p>
  <strong>Proficiency date:</strong>
  <%= @award.proficiency_date %>
</p>

<p>
  <strong>Expiry date:</strong>
  <%= @award.expiry_date %>
</p>

<p>
  <strong>Award allocation date:</strong>
  <%= @award.award_allocation_date %>
</p>

<p>
  <strong>Proficiency allocation date:</strong>
  <%= @award.proficiency_allocation_date %>
</p>

<p>
  <strong>Originating organisation:</strong>
  <%= @award.originating_organisation %>
</p>

<%= link_to 'Edit', edit_award_path(@award) %> |
<%= link_to 'Back', awards_path %>